import numpy as np
array1 = np.zeros(3)
array2 = np.zeros((1,4))
array3 = np.zeros((2,5))
print(type(array1))
print(type(array2))
print(type(array2[0][0]))
array4 = np.arange(10)
array5 = np.arange(10,20)
array6 = np.arange(10,30,4)
print(array4)
print(array5)
print(array6)
vector = np.arange(5)
print(vector.shape) 
matrix = np.ones([3,2])
print(matrix)
print(matrix.shape)
tensor = np.zeros([2,3,3])
print(tensor)
print(tensor.shape)
arr = [1,2,3,4,5,6]
arr = np.array(arr)
arr = arr.reshape(3, 2)  
print(arr)
arr1 = arr.reshape(6)   
print(arr1)
arr2 = arr.reshape(2, 3) 
print(arr2)
arr1 = np.arange(1, 10)
arr2 = np.arange(2, 25, 2)
arr3 = arr1.reshape(3, -1)
arr4 = arr2.reshape(4, -1)
arr5 = arr2.reshape(2, -1)
arr6 = arr2.reshape(3, -1)
arr7 = arr2.reshape(-1, 4) # Numpy predicts and fixes number of rows


print('Arr1:\n', arr1)
print('Arr2:\n', arr2)
print('Arr3:\n', arr3)
print('Arr4:\n', arr4)
print('Arr5:\n', arr5)
print('Arr6:\n', arr6)
print('Arr7:\n', arr7)

